name: erp_umkm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

#==================================================
# DEPENDENCIES (PAKET APLIKASI UTAMA)
#==================================================
dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  # Firebase (Backend)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  geolocator: ^14.0.2
  # Fungsional
  image: ^4.5.4
  image_picker: ^1.2.1
  fl_chart: ^1.1.1

  intl: ^0.20.2
  
  # Printer
  blue_thermal_printer: ^1.2.3

  # State Management
  provider: ^6.1.5+1

  shared_preferences: ^2.5.3

  # Ikon
  cupertino_icons: ^1.0.8

  url_launcher: ^6.3.2
  
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0

#==================================================
# DEV DEPENDENCIES (ALAT PENGEMBANGAN)
#==================================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # PENTING: Package ini sebaiknya di dev_dependencies
  flutter_launcher_icons: ^0.14.4

#==================================================
# PENGATURAN FLUTTER
#==================================================
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/qris_dana.jpg

#==================================================
# KONFIGURASI ICON (HARUS DI PALING KIRI/ROOT)
#==================================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Ezzen_Icons.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/Ezzen_Icons.png"
    background_color: "#ffffff" # Saya beri default putih agar valid
    theme_color: "#ffffff"